apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erp-dev
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: erp
  source:
    repoURL: https://github.com/reyptz/lab-sysadmin-sec.git
    targetRevision: main
    path: platform/gitops/argocd/apps/erp/overlays/dev
  destination:
    server: https://kubernetes.default.svc
    namespace: erp-dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
