apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: erp-prod-canary
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: erp
  source:
    repoURL: https://github.com/reyptz/lab-sysadmin-sec.git
    targetRevision: main
    path: platform/gitops/argocd/apps/erp/overlays/prod-canary
  destination:
    server: https://kubernetes.default.svc
    namespace: erp-prod
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
