apiVersion: v1
kind: ServiceAccount
metadata:
  name: erp-app
  namespace: erp-prod
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: erp-app
  namespace: erp-staging
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: erp-app
  namespace: erp-dev
automountServiceAccountToken: false
