apiVersion: platform.lab/v1alpha1
kind: PostgreSQL
metadata:
  name: invoices-db
  namespace: billing
spec:
  parameters:
    size: small
    storage: 20
    database: invoices
    backupRetention: 7
  compositionSelector:
    matchLabels:
      provider: aws
  writeConnectionSecretToRef:
    name: invoices-db-connection
    namespace: billing
