apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: erp-db-credentials
  namespace: erp-prod
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: SecretStore
    name: erp-aws-secrets
  target:
    name: erp-db-credentials
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: host
      remoteRef:
        key: erp/prod/db
        property: host
    - secretKey: port
      remoteRef:
        key: erp/prod/db
        property: port
    - secretKey: username
      remoteRef:
        key: erp/prod/db
        property: username
    - secretKey: password
      remoteRef:
        key: erp/prod/db
        property: password
    - secretKey: database
      remoteRef:
        key: erp/prod/db
        property: database
