apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: erp-aws-secrets
  namespace: erp-prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-3
      auth:
        jwt:
          serviceAccountRef:
            name: erp-app
