apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: erp-aws-secrets
  namespace: erp-prod
spec:
  provider:
    aws:
      service: SecretsManager
      region: eu-west-3
      auth:
        jwt:
          serviceAccountRef:
            name: erp-app
---
# Exemple Azure Key Vault
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: erp-azure-secrets
  namespace: erp-prod
spec:
  provider:
    azurekv:
      vaultUrl: https://erp-prod-kv.vault.azure.net
      authType: WorkloadIdentity
      serviceAccountRef:
        name: erp-app
