apiVersion: apps/v1
kind: Deployment
metadata:
  name: erp-app-vault-example
  namespace: erp-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: erp-app
  template:
    metadata:
      labels:
        app: erp-app
      annotations:
        vault.hashicorp.com/agent-inject: 'true'
        vault.hashicorp.com/role: 'erp-app'
        vault.hashicorp.com/agent-inject-secret-db.conf: 'secret/erp/prod/db'
        vault.hashicorp.com/template-static-secret-render-once: 'true'
    spec:
      serviceAccountName: erp-app
      containers:
        - name: erp-app
          image: ghcr.io/reyptz/lab-sysadmin-sec/erp-app:latest
          env:
            - name: DB_CONFIG_PATH
              value: /vault/secrets/db.conf
