apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: erp-prod

resources:
  - ../../base/service.yaml
  - analysis-template.yaml
  - rollout.yaml

images:
  - name: erp-app
    newTag: prod-latest
