apiVersion: "serving.kserve.io/v1beta1"
kind: "InferenceService"
metadata:
  name: "risk-default-payment"
  namespace: mlops
  annotations:
    serving.kserve.io/deploymentMode: "Serverless"
spec:
  predictor:
    model:
      modelFormat:
        name: sklearn
      storageUri: "s3://mlflow-models/risk-default-payment/1/model"
      resources:
        limits:
          cpu: "1"
          memory: 2Gi
        requests:
          cpu: "100m"
          memory: 512Mi
    minReplicas: 1
    maxReplicas: 5
    containerConcurrency: 100
  transformer:
    containers:
      - name: transformer
        image: ghcr.io/myorg/risk-transformer:latest
        resources:
          limits:
            cpu: "500m"
            memory: 512Mi
          requests:
            cpu: "100m"
            memory: 256Mi
